# Fetch Rewards Coding Exercise - Data Analyst

## First: Review Existing Unstructured Data and Diagram a New Structured Relational Data Model

Diagram submitted as schema.png file

In [1]:
import json
from psycopg2 import connect, Error

In [2]:
brands = []
print("Started Reading JSON file which contains multiple JSON document")
with open('/Users/devanshoojain/RPI_Sem_2/Fetch_rewards/fetch_rewards/brands.json') as json_data:
    for jsonObj in json_data:
        brandsdict = json.loads(jsonObj)
        brands.append(brandsdict)

Started Reading JSON file which contains multiple JSON document

In [3]:
for brand in brands:
    print(brand["_id"]["$oid"])

601ac115be37ce2ead437551
601c5460be37ce2ead43755f
601ac142be37ce2ead43755d
601ac142be37ce2ead43755a
601ac142be37ce2ead43755e
601ac142be37ce2ead43755b
601ac142be37ce2ead43755c
5cdad0f5166eb33eb7ce0faa
5ab15636e4b0be0a89bb0b07
5c408e8bcd244a1fdb47aee7
5f4bf556be37ce0b4491554d
57c08106e4b0718ff5fcb02c
588ba07be4b02187f85cdadd
5d6413156d5f3b23d1bc790a
585a9611e4b03e62d1ce0e74
57e5820ce4b0ac389136a311
5fb6adb8be37ce522e165cb8
5f358338be37ce443bf9d55a
5fb28549be37ce522e165cb5
592486bfe410d61fcea3d139
5c4699f387ff3577e203ea29
5da6071ea60b87376833e34d
57ebc011e4b0ac389136a335
5332f5fee4b03c9a25efd0bd
5332fa7ce4b03c9a25efd22e
5e9f18bfbe37ce3e45b6a77f
592486bee410d61fcea3d133
5d66d71fa3a018093ab34728
5f493e72be37ce64d0ae36c6
5f4936ddbe37ce52f8314fd9
57ebc2e7e4b0ac389136a34b
5fd2a0aebe37ce49eb72c0ee
5dc03596a60b873d6b0666cd
5f494c5f04db711dd8fe87e6
5332f772e4b03c9a25efd125
59dfaad1e4b0a56a2fa69abc
5daf33e71dda2c3e1416ae93
5f35a0babe37ce6853cff1ff
5fd29590be37ce38bbbefb28
5fd3acb6be37ce0d9386bb40
5bd200a6965c7d66d92731ea
585a9675e4b03e62d1ce0e7f
5887a17ee4b02187f85cdad3
5332f765e4b03c9a25efd11f
5d66d94d6d5f3b6188d4f04b
5d66d2fd6d5f3b6188d4f045
5332f5f3e4b03c9a25efd0ad
5fa1c567be37ce402c4618f1
5a5d1e76e4b0db471c2d0425
55b630d9e4b0d8e685c1421f
5d602d9d6d5f3b23d1bc7907
57ebbf75e4b0ac389136a32f
5d2f68d96d5f3b107e208da4
592486bde410d61fcea3d124
5f16f536be37ce2b30061e27
5332f6ede4b03c9a25efd0e5
5332fa05e4b03c9a25efd1d6
5f3d6f44be37ce4ddbb1bb3e
5c76d3cd95144c5375687b4f
5f3ff223be37ce1c81aa1e11
5a8c36dbe4b0ccf165fac9e9
55b630e1e4b0d8e685c14220
5f3ff222be37ce1c81aa1e0f
5c76db7295144c5375687b50
5da609991dda2c3e1416ae90
5afda575e4b0c11cfecd49f9
5ab154dde4b0915382df761f
5f3e9195be37ce5a0e01b960
5fb82faebe37ce522e165ce9
57e58157e4b0ac389136a30a
5fd3acb6be37ce0d9386bb41
5e90a545ee7f2d70340f40d7
5daf5e94a60b87376833e362
5fb2852cbe37ce522e165caf
5332f743e4b03c9a25efd109
5fa98944be37ce239d107100
5afda65de4b0c11cfecd49fb
5332fa7ee4b03c9a25efd230
57ebbfafe4b0ac389136a332
5f493682be37ce52f8314fce
57ace91ae4b057c992a316ac
5a5d2431e4b06ba572cf24a1
57e5810ce4b0ac389136a307
5332f5f2e4b03c9a25efd0ab
5db9f9cca60b87376833e36b
5fd2a0c0be37ce49eb72c0f4
5aa1b41de4b086c8aad5e096
592486bee410d61fcea3d136
5332f603e4b03c9a25efd0be
5afda699e4b0c11cfecd49fd
5fc54c0bbe37ce1911dbb3b5
5f358338be37ce443bf9d55b
592486bfe410d61fcea3d137
5a4d2295e4b0d5c3fd86b679
5f628216be37ce78e6e2efaf
5332f9fce4b03c9a25efd1cd
5f9770bfbe37ce03d08a2d85
57ebc293e4b0ac389136a345
5f513e9ebe37ce21f1287c00
5332f7b8e4b03c9a25efd145
5ab153fee4b0915382df761e
5aa1b5b9e4b05a92fc9b1631
5f3e9172be37ce5a0e01b954
5f4936ddbe37ce52f8314fdc
57c0829ce4b0718ff5fcb03a
5a4d244ae4b0bcb2c74ea77f
57ebbfa1e4b0ac389136a330
5f43faabbe37ce3ef3fd3715
59d550f4e4b090070b009534
585a9645e4b03e62d1ce0e79
585a968ee4b03e62d1ce0e82
5d2f6b82a3a01810a2174aed
5fa98944be37ce239d1070fe
5332f9f2e4b03c9a25efd1c8
55a41b55e4b0d0a65b3692ef
5887a372e4b02187f85cdad9
57ed0697e4b072ac2294b8f2
55b630c2e4b0d8e685c1421d
5332f605e4b03c9a25efd0c0
5f43faabbe37ce3ef3fd3716
5d66de49a3a018093ab3472a
5da605dc1dda2c3e1416ae83
5e3876bfee7f2d697e835bd3
5fa98945be37ce239d107104
57ebc11fe4b0ac389136a33a
5f494c5f04db711dd8fe87e5
5bd201a990fa074576779a19
5fb2852cbe37ce522e165cb1
5332f60ce4b03c9a25efd0c3
5a7e0604e4b0aedb3b84afd3
5332f9f2e4b03c9a25efd1c7
57ebbd44e4b0ac389136a32d
592486bee410d61fcea3d12f
592486bee410d61fcea3d12a
5da60576a60b87376833e349
5332f5f5e4b03c9a25efd0b0
580dff9fe4b0f32b2de21382
5da608131dda2c3e1416ae8a
588b9f8fe4b02187f85cdada
592486bde410d61fcea3d127
5a4d23dae4b0bcb2c74ea77e
5d66dc946d5f3b6188d4f04e
592486bfe410d61fcea3d140
5d658ff3a3a018514994f432
5fcda494be37ce688e08b0cc
5ef4f667be37ce2efae842ea
55b6308ee4b0d8e685c1421a
5332f760e4b03c9a25efd11b
5f16f536be37ce2b30061e29
5d642dbfa3a018514994f42e
5e3875d2ee7f2d697e835bce
5332f9f3e4b03c9a25efd1c9
5c45f91b87ff3552f950f027
58861c7d4e8d0d20bc42c4d6
55b630fde4b0d8e685c14223
5ab158e8e4b0915382df7622
5fcda494be37ce688e08b0cf
5f3ff222be37ce1c81aa1e0e
5f772952be37ce6b592e90d2
5fa1c568be37ce402c4618f6
5fb82236be37ce522e165cdf
5a02188be4b00d6a5ccb394d
5e387617ee7f2d697e835bd0
57ebc2ace4b0ac389136a346
5da6094ca60b87376833e357
5f16f536be37ce2b30061e28
5f872b84be37ce66db5dd97a
585a9726e4b03e62d1ce0e95
5f7ba645be37ce23081c528d
5332f7d3e4b03c9a25efd14e
5f504acabe37ce0b793c9418
5afda3a8e4b03bf01c2a2967
57c08294e4b0718ff5fcb039
5332f77ce4b03c9a25efd12a
5332f9ede4b03c9a25efd1c2
58861c7e4e8d0d20bc42c4e2
592486bee410d61fcea3d12d
5da608dfa60b87376833e354
5ffe3a87be37ce7aab2d4fd9
5ffe3a87be37ce7aab2d4fdb
5ffe3a86be37ce7aab2d4fd7
5fff3a7abe37ce2bb793010e
5ffe3a86be37ce7aab2d4fd8
5ffe3a86be37ce7aab2d4fd6
5ffe35eabe37ce5e01754c47
5ffe347ebe37ce5e01754c3f
5ffe35eabe37ce5e01754c48
57ebc28be4b0ac389136a344
58b59989e4b0857c2ddb7255
5f403232be37ce5f78d9ed19
5f493e72be37ce64d0ae36c4
5a5d257fe4b06ba572cf24a3
585a963ce4b03e62d1ce0e78
5fb82a68be37ce522e165ce6
5d6415d5a3a018514994f429
5332fa7ae4b03c9a25efd229
5f494c5e04db711dd8fe87e4
5f772951be37ce6b592e90d0
5f504ac2be37ce0b793c9415
5bd201cc965c7d66d92731ee
5fd2a0bfbe37ce49eb72c0f1
5daf3507a60b87376833e35c
58861c7e4e8d0d20bc42c4de
5f9770c0be37ce03d08a2d88
5a5e32c3e4b06ba572cf24aa
5f99f71bbe37ce13da9eade9
5ffe35eabe37ce5e01754c4a
5ffe3682be37ce5e01754c55
5ffe347ebe37ce5e01754c41
5ffe347ebe37ce5e01754c40
5ffe3480be37ce5e01754c44
5ffe35eabe37ce5e01754c46
5ffe35f9be37ce5e01754c4c
5ffe347fbe37ce5e01754c42
5ffe35eabe37ce5e01754c49
5ff768e3be37ce1e961f32a0
5ff768d4be37ce1e961f329b
5ff768d4be37ce1e961f329d
5ff768d4be37ce1e961f329c
5ff768d4be37ce1e961f329e
5ff77857be37ce58ce50083a
5fd7f2b3be37ce733975586c
5fd7f2b3be37ce733975586b
5fd7f2b3be37ce733975586a
5fd7f2b8be37ce733975586f
5fd7f2b4be37ce733975586d
5fd3acb6be37ce0d9386bb3f
5332fa7be4b03c9a25efd22b
58861c7e4e8d0d20bc42c4e0
5332f775e4b03c9a25efd127
581ce962e4b058c71f74c443
5332fa08e4b03c9a25efd1d8
5f3d6f44be37ce4ddbb1bb3b
5f628235be37ce78e6e2efb1
58b5988ce4b0857c2ddb7252
5f3ff200be37ce1c81aa1e0b
57ebc125e4b0ac389136a33b
5332f7c8e4b03c9a25efd148
57ebc2c8e4b0ac389136a349
588ba032e4b02187f85cdadc
5f493665be37ce52f8314fca
5dc0773ea60b873d6b0666ce
5da60649a60b87376833e34b
580dff84e4b0f32b2de2137f
5fcff305be37ce6d53dfc688
5d66961cee7f2d201c7281cc
57d957f2e4b0ac389136a2b4
5daf59751dda2c3e1416ae99
5da60859a60b87376833e352
5fb81935be37ce522e165cda
5fb6d726be37ce522e165cc0
5fb800f1be37ce522e165ccb
5fb80b63be37ce522e165cd1
5fb808a1be37ce522e165ccf
5fb7e62dbe37ce522e165cc3
5fb80d7cbe37ce522e165cd2
5fb7e962be37ce522e165cc6
5d642de76d5f3b23d1bc7911
57c0827de4b0718ff5fcb037
5f3d6f44be37ce4ddbb1bb3d
5fa1c567be37ce402c4618f0
5332fa03e4b03c9a25efd1d5
5a8c3577e4b07f0a2dac8945
5da60932a60b87376833e356
5da606581dda2c3e1416ae85
5a5d1ba9e4b0db471c2d0422
585a9714e4b03e62d1ce0e92
57ebc026e4b0ac389136a338
5da608a8a60b87376833e353
5fcda47cbe37ce688e08b0c3
5d66dda06d5f3b6188d4f050
585a9637e4b03e62d1ce0e77
5332fa79e4b03c9a25efd226
5fb82359be37ce522e165ce1
592486bfe410d61fcea3d13f
552ecca1e4b02ff29f99b215
5a5e3615e4b06ba572cf24ab
5e5ff1f7ee7f2d0b35b2a18e
585a967fe4b03e62d1ce0e80
5f513ea1be37ce21f1287c02
5d66dd526d5f3b6188d4f04f
5d6412f86d5f3b23d1bc7909
5332f608e4b03c9a25efd0c1
5c49d161f0276e7719673719
5da60843a60b87376833e351
5f7ba648be37ce23081c528e
5a5d29fde4b0db471c2d0433
54594387e4b0bfcb1e864083
585a96d2e4b03e62d1ce0e89
5332f9fee4b03c9a25efd1d0
5332fa73e4b03c9a25efd21c
5fa98944be37ce239d107103
5332f7afe4b03c9a25efd13d
5d540e65a3a018514994f41f
5daf46261dda2c3e1416ae96
585a972de4b03e62d1ce0e96
5f9770bfbe37ce03d08a2d86
580e015be4b0f32b2de21385
5f5900d4be37ce21f1287c11
5a8c33f3e4b07f0a2dac8943
5ab1589ae4b0915382df7621
5afda22ee4b03bf01c2a2965
588b9ff4e4b02187f85cdadb
5ec2dde7be37ce5234ec36bb
5ff78071be37ce6a424ca0e9
5ff78071be37ce6a424ca0e8
5ff78071be37ce6a424ca0ea
5ff78072be37ce6a424ca0ec
5ff78071be37ce6a424ca0eb
5ff789c5be37ce786ba0f6a3
5ff77857be37ce58ce50083c
5ff77858be37ce58ce50083d
5ff78070be37ce6a424ca0e6
5ff77857be37ce58ce50083b
5ff77859be37ce58ce500840
5ff77859be37ce58ce50083e
5bd200c690fa074576779a16
5fdce9eabe37ce5fa8ba59db
5fdce9e9be37ce5fa8ba59da
5fdce9e9be37ce5fa8ba59d7
5fdce9e9be37ce5fa8ba59d9
5fdce9e9be37ce5fa8ba59d8
5daf35a8a60b87376833e35d
5f4936ddbe37ce52f8314fdd
5f4936ddbe37ce52f8314fde
5fb6b82dbe37ce522e165cbc
5d641306a3a018514994f427
55b630f5e4b0d8e685c14222
5db780a6a60b87376833e369
5f4936ddbe37ce52f8314fdb
5332f5f2e4b03c9a25efd0a9
5fb2852cbe37ce522e165cb2
592486bee410d61fcea3d12e
57c082a6e4b0718ff5fcb03b
5da606ae1dda2c3e1416ae86
5f99f71bbe37ce13da9eade7
5a8c5e74e4b07f0a2dac8947
57e5817ae4b0ac389136a30c
5ab15392e4b0915382df761d
5e5ff265ee7f2d0b35b2a18f
5f16f536be37ce2b30061e25
5332fb83e4b03c9a25efd24a
5ef38672be37ce02da95b72f
5daf6baaa60b87376833e364
5a4d1f06e4b0d5c3fd86b678
57ebc003e4b0ac389136a333
5f441280be37ce5dbe9b7c80
5ec2dda8be37ce5234ec36ba
58861c7f4e8d0d20bc42c4f9
58b59a68e4b0857c2ddb7257
5332f753e4b03c9a25efd10f
5a4d250ce4b0d5c3fd86b67b
5d9d0270a60b87376833e347
5d658fd1a3a018514994f431
5f358338be37ce443bf9d55c
58b599fee4b0857c2ddb7256
5a5d278de4b0db471c2d042f
5332f7eee4b03c9a25efd15e
5afda18ee4b0c11cfecd49f5
5a8c363ce4b0ccf165fac9e7
5dd557081dda2c1971449a7a
5332f774e4b03c9a25efd126
5f4802bdbe37ce0c8303373f
5a021703e4b00efe02b02a58
5dc2da1fa60b873d6b0666d3
5d2f69a6a3a01810a2174aec
5f208dafbe37ce7958c59522
5f2336cfbe37ce7958c5952c
5f3e9172be37ce5a0e01b953
55a41b88e4b0d0a65b3692f0
5daf70071dda2c3e1416ae9e
5a8c31bfe4b0ccf165fac9e4
5f7760f0be37ce1d26d7b7a5
5f99f71bbe37ce13da9eadea
5a8c378ce4b07f0a2dac8946
5f493682be37ce52f8314fd0
580dff97e4b0f32b2de21381
5f38578fbe37ce5178517ad7
5fd2a0bfbe37ce49eb72c0f0
5332fa6be4b03c9a25efd217
5a8f64c6e4b0a2e2844f5695
5f493dabbe37ce64d0ae36bd
57ebc134e4b0ac389136a33d
5f5bc4f1be37ce17125ac0ea
5fd29591be37ce38bbbefb2a
5f77274bbe37ce6b592e90bc
5a8c35dde4b0ccf165fac9e6
5332f760e4b03c9a25efd11a
5f4802d2be37ce0c83033743
60074277be37ce360be639ff
5332f9f0e4b03c9a25efd1c3
5fb2852cbe37ce522e165cb0
58861c7e4e8d0d20bc42c4e3
585b0b23e4b03e62d1ce0e99
5332f7ffe4b03c9a25efd16a
5da608291dda2c3e1416ae8b
57d848efe4b0ac389136a2aa
5f513ea1be37ce21f1287c03
5f35a0babe37ce6853cff201
5a5d2c1fe4b06ba572cf24a8
5d603537a3a018514994f424
5da607a9a60b87376833e34f
5f493682be37ce52f8314fcd
585a970ee4b03e62d1ce0e91
5f403231be37ce5f78d9ed18
5f7ba932be37ce2f290fb252
58863e1ee4b02187f85cdace
5a5d234be4b06ba572cf249f
5d642d946d5f3b23d1bc7910
5fb8292abe37ce522e165ce3
5d6419346d5f3b23d1bc790e
5332fa0ae4b03c9a25efd1dd
5ccb2ece166eb31bbbadccbe
60074278be37ce360be63a03
5d6419746d5f3b23d1bc790f
5a5d1fbfe4b0db471c2d0428
5f3d6f44be37ce4ddbb1bb3c
580dffade4b0f32b2de21384
5d6423ffa3a018514994f42c
5f9770bfbe37ce03d08a2d84
5f4a7a5dbe37ce2d95e65ca3
5f35834dbe37ce443bf9d565
592486bfe410d61fcea3d13d
5daf3365a60b87376833e35b
5a5d2a86e4b06ba572cf24a6
5d6415c66d5f3b23d1bc790c
57c08285e4b0718ff5fcb038
5f208dafbe37ce7958c59523
5c9a975495144c182bbc7270
5332f709e4b03c9a25efd0f0
5dc1aaf51dda2c0ad7da64ad
58861c7f4e8d0d20bc42c4f8
5fda3724be37ce09e3515970
5fda3725be37ce09e3515974
5fda3724be37ce09e3515971
5fd28f0cbe37ce6d53dfc692
5fda3724be37ce09e3515972
5fda3724be37ce09e3515973
5ff73cffbe37ce1e961f325d
5ff73cf9be37ce1e961f3258
5ff73cf9be37ce1e961f325a
5ff74123be37ce1e961f3266
5ff73cf9be37ce1e961f3259
5ff73cfabe37ce1e961f325b
5ff74500be37ce1e961f3279
5ff74500be37ce1e961f327b
5ff75cdebe37ce1e961f328b
5ff74500be37ce1e961f3278
5ff74500be37ce1e961f327a
5ff74500be37ce1e961f3277
5da60785a60b87376833e34e
6000a0c9be37ce2bb7930121
6000a0c6be37ce2bb793011f
6000b8c3be37ce321363c6c0
6000a0c6be37ce2bb7930120
6000a0f3be37ce2bb793012a
6000a0c6be37ce2bb793011e
5f7760f2be37ce1d26d7b7a7
5332f7ace4b03c9a25efd13a
5daf5d1aa60b87376833e361
5f7760f0be37ce1d26d7b7a4
5afda26ce4b0c11cfecd49f8
592486bee410d61fcea3d130
57c0812de4b0718ff5fcb02e
5a5d1c62e4b0db471c2d0424
5fcda494be37ce688e08b0d0
57ebbcc2e4b0ac389136a32c
5c409ab4cd244a3539b84162
5daf54ec1dda2c3e1416ae98
5f19e054be37ce33f74a166f
5d658fc0a3a018514994f430
585a966be4b03e62d1ce0e7e
5f872b7fbe37ce66db5dd976
5a5d24c2e4b0db471c2d042b
5332f7e0e4b03c9a25efd151
5db77d891dda2c3e1416ae9f
5f21c852be37ce7958c59529
5bcdfc5a965c7d66d92731e9
5f494c5e04db711dd8fe87e3
5f872b7fbe37ce66db5dd978
57ebc017e4b0ac389136a336
5f77274cbe37ce6b592e90be
5f99f71bbe37ce13da9eadeb
5ab15207e4b0be0a89bb0b04
5332f5f6e4b03c9a25efd0b2
5f493682be37ce52f8314fcf
5f7760f0be37ce1d26d7b7a3
58861c7f4e8d0d20bc42c500
5cc725bd166eb31bbbadccbd
5f3e9173be37ce5a0e01b957
585a96b3e4b03e62d1ce0e85
5332f6f4e4b03c9a25efd0ed
5d642dd1a3a018514994f42f
5332f802e4b03c9a25efd16d
5ef3860fbe37ce02da95b72e
585a9698e4b03e62d1ce0e83
5a5e36d6e4b06ba572cf24ac
5f5bc4f1be37ce17125ac0eb
55bf8c6ce4b0d8e685c1489d
5f358338be37ce443bf9d558
5a8c3140e4b07f0a2dac8941
5a5d17ede4b06ba572cf2498
5a5d23f1e4b06ba572cf24a0
5f628215be37ce78e6e2efad
58861c7e4e8d0d20bc42c4f6
580dff8fe4b0f32b2de21380
5d66d516a3a018093ab34725
5daf4f9ca60b87376833e360
5daf6e31a60b87376833e365
5332f7ace4b03c9a25efd13b
5f3ff222be37ce1c81aa1e10
5d66d8c86d5f3b6188d4f049
5fcff319be37ce6d53dfc691
5332fa74e4b03c9a25efd21e
5f4802bdbe37ce0c83033740
585a96e9e4b03e62d1ce0e8b
5332f756e4b03c9a25efd113
5afda67de4b0c11cfecd49fc
5f4bf556be37ce0b4491554c
5fa1c567be37ce402c4618f3
5ab15669e4b0be0a89bb0b08
5332f612e4b03c9a25efd0c4
5f21ca86be37ce7958c5952b
57e580e8e4b0ac389136a304
58861c7e4e8d0d20bc42c4f7
5332fa84e4b03c9a25efd232
5d2f3eada3a01810a2174aeb
5daf63151dda2c3e1416ae9b
5f772952be37ce6b592e90d5
55bf8c15e4b0d8e685c1489c
5f7ba645be37ce23081c528c
5da605bea60b87376833e34a
5f493e72be37ce64d0ae36c5
5fd3acb6be37ce0d9386bb43
5952a596e4b08f39def64d03
5f3ff222be37ce1c81aa1e0d
5d6027f46d5f3b23d1bc7906
5f77274bbe37ce6b592e90bb
5afda1dae4b0c11cfecd49f6
5e710dbeee7f2d0b35b2a192
5d66dad8a3a018093ab34729
5daf5f65a60b87376833e363
5f4802bdbe37ce0c8303373d
5ffe3381be37ce5e01754c35
5ffe2e38be37ce5e01754c23
5ffe347ebe37ce5e01754c3e
5ffe336fbe37ce5e01754c31
5ffe336fbe37ce5e01754c32
5ffe336fbe37ce5e01754c30
5ffe2e39be37ce5e01754c24
5ffe2e39be37ce5e01754c26
5ffe2e39be37ce5e01754c25
5ffe336fbe37ce5e01754c2f
5ffe336fbe37ce5e01754c33
5fdce8dbbe37ce5fa8ba59c2
5fdce8dbbe37ce5fa8ba59c1
5fdce8dcbe37ce5fa8ba59c3
5fdce9cabe37ce5fa8ba59ce
5fdce8edbe37ce5fa8ba59cc
5fdce8dbbe37ce5fa8ba59bf
5fdce8dbbe37ce5fa8ba59c0
5fb8216ebe37ce522e165cdd
5332f765e4b03c9a25efd120
5f43faabbe37ce3ef3fd3717
5a5d1f46e4b0db471c2d0427
5db9e8db1dda2c3e1416aea1
57ebc2bde4b0ac389136a348
5a02196ce4b00efe02b02a5a
5a5d2bcbe4b0db471c2d0435
57d9580ee4b0ac389136a2b6
5c112616315a241ba1716511
5f403231be37ce5f78d9ed17
5fd3acb6be37ce0d9386bb42
5db20be5a60b87376833e366
5d9d08d1a60b87376833e348
5daf54491dda2c3e1416ae97
5332f734e4b03c9a25efd103
53501d29b9237fd7718f9e15
5332f775e4b03c9a25efd128
5f38576ebe37ce5178517acb
5c76dd4d95144c5375687b52
585a964ce4b03e62d1ce0e7a
5f59002dbe37ce21f1287c10
5f4802bdbe37ce0c8303373e
5f493dacbe37ce64d0ae36bf
5f38578fbe37ce5178517ad6
5332fa7be4b03c9a25efd22c
5d6412e9a3a018514994f426
5332f7b4e4b03c9a25efd140
5fb821d1be37ce522e165cde
5457a0cde4b05a46170caebc
5332f7f5e4b03c9a25efd163
5f590184be37ce21f1287c12
5f403231be37ce5f78d9ed16
57ebc01fe4b0ac389136a337
5f772952be37ce6b592e90d6
5f298852be37ce7958c5952d
57ebc144e4b0ac389136a33f
5f772952be37ce6b592e90d3
5332fa7ce4b03c9a25efd22d
5f77274bbe37ce6b592e90bd
5f19e062be37ce33f74a1675
5d66def56d5f3b6188d4f051
5a5d1a67e4b06ba572cf2499
5da608c91dda2c3e1416ae8d
5fcff304be37ce6d53dfc687
5f4936debe37ce52f8314fdf
5f441280be37ce5dbe9b7c7e
5daf329ca60b87376833e35a
5f4cff1ba475f1050a66b568
5f4bf556be37ce0b4491554b
5db6fb28a60b87376833e367
5f3d6f43be37ce4ddbb1bb39
5cdacf1c166eb33eb7ce0fa9
53501d29b9237fd7718f9e17
5afda00ce4b0c11cfecd49f4
5f4cff1aa475f1050a66b567
5332f9fde4b03c9a25efd1cf
5f4a64e7be37ce17d23b317b
5db77f7aa60b87376833e368
592486bee410d61fcea3d135
58861c7f4e8d0d20bc42c4fd
5a5d1a8ce4b0db471c2d0420
57ebc15fe4b0ac389136a342
5332f9fce4b03c9a25efd1cc
57c08250e4b0718ff5fcb033
5f21c99dbe37ce7958c5952a
5d6412d36d5f3b23d1bc7908
5bd2011f90fa074576779a17
5f4a64e7be37ce17d23b3179
5332fa7de4b03c9a25efd22f
5fb2852dbe37ce522e165cb3
5a8c2e5ee4b0ccf165fac9e1
5f4cff1ca475f1050a66b56a
5f7ba932be37ce2f290fb253
58861c7e4e8d0d20bc42c4e9
5f4802bebe37ce0c83033741
5332fa67e4b03c9a25efd216
55a41a9de4b0d0a65b3692ed
5fcff304be37ce6d53dfc685
5db9f8c5a60b87376833e36a
5332f789e4b03c9a25efd12c
5f3d6f45be37ce4ddbb1bb3f
5332f762e4b03c9a25efd11e
5f16f512be37ce2b30061e1e
5daf2baea60b87376833e359
57d95741e4b0ac389136a2b1
5332f7b2e4b03c9a25efd13f
5f35a0babe37ce6853cff200
537b7ec2892471241348d70a
5fc54c0abe37ce1911dbb3b3
5d642d65a3a018514994f42d
5fb829c0be37ce522e165ce4
5dc2db051dda2c0ad7da64b0
5f35a0babe37ce6853cff1fe
5332f5fde4b03c9a25efd0bc
5d66e20b6d5f3b6188d4f055
5332f9f4e4b03c9a25efd1ca
5d6594a2a3a018514994f434
5f5bc4f1be37ce17125ac0ec
55b630d3e4b0d8e685c1421e
5ab154eae4b0915382df7620
55b630ece4b0d8e685c14221
5cdad1daca6a4c76f3f8c515
592486bee410d61fcea3d128
5f7ba645be37ce23081c528a
5f358338be37ce443bf9d559
5f494cf904db711dd8fe87f0
57d96124e4b0ac389136a2b9
5da60696a60b87376833e34c
5332f603e4b03c9a25efd0bf
591325cde4b0cddf4ebb6a69
5d4880ca6d5f3b105d1bc8dc
585a9744e4b03e62d1ce0e98
585a96fbe4b03e62d1ce0e8e
5daf68751dda2c3e1416ae9c
5da607daa60b87376833e350
5332f9f1e4b03c9a25efd1c5
5887a28ae4b02187f85cdad6
592486bee410d61fcea3d12b
5aa1b53ae4b086c8aad5e097
5fa98944be37ce239d107101
5d6417f56d5f3b23d1bc790d
592486bee410d61fcea3d129
588ba0f5e4b02187f85cdade
5f4bf556be37ce0b4491554a
5f7760ffbe37ce1d26d7b7a9
5332f5fbe4b03c9a25efd0b9
5daf2e2a1dda2c3e1416ae92
5332f9fde4b03c9a25efd1ce
5a8f6461e4b02d0314ffa208
58861d07e4b02187f85cdacd
5f504ac2be37ce0b793c9412
5332f7aae4b03c9a25efd139
53501d29b9237fd7718f9e16
5fd29590be37ce38bbbefb27
5c49d4c5315a247b580d50fb
5f208dafbe37ce7958c59524
592486bde410d61fcea3d126
585a971ae4b03e62d1ce0e93
5332f7a9e4b03c9a25efd137
5a5d1e5fe4b06ba572cf249d
5332f77de4b03c9a25efd12b
57dd5a50e4b0ac389136a2d9
5fa1c568be37ce402c4618f4
5f4a7a60be37ce2d95e65cad
5f19e054be37ce33f74a1671
5fd29591be37ce38bbbefb2c
5332fa7ae4b03c9a25efd228
5f441281be37ce5dbe9b7c82
57ebc158e4b0ac389136a341
5332fa73e4b03c9a25efd21d
57ebc009e4b0ac389136a334
5fb6b695be37ce522e165cba
5f872b7fbe37ce66db5dd977
5a5d1e8fe4b06ba572cf249e
5d658fde6d5f3b23d1bc7913
5f4a7a5ebe37ce2d95e65ca4
57c08268e4b0718ff5fcb035
5a5d2856e4b0db471c2d0430
591b7682e4b0cddf4ebb6a6a
585a965be4b03e62d1ce0e7c
585a96c2e4b03e62d1ce0e87
55b6309ce4b0d8e685c1421b
5d641257a3a018514994f425
5a7e0c1ae4b0782f27c68d4e
5fc54c17be37ce1911dbb3b8
5ab130e2e4b0915382df7619
5f504ac2be37ce0b793c9413
5d66dbf36d5f3b6188d4f04d
5332f7f0e4b03c9a25efd160
5f9770bfbe37ce03d08a2d87
5332f9f1e4b03c9a25efd1c4
5332f7a8e4b03c9a25efd136
5d5abca1a3a018514994f421
5f19e054be37ce33f74a1670
5dc07de6a60b873d6b0666d0
5d66dfec6d5f3b6188d4f053
5a5d209ae4b0db471c2d0429
5a5d1d05e4b06ba572cf249b
5d601d74a3a018514994f422
60074277be37ce360be63a01
58861c7e4e8d0d20bc42c4ea
5f3e9172be37ce5a0e01b956
540f241c68abd3c7065097d5
5ab13217e4b0915382df761b
5fd3acb9be37ce0d9386bb4c
53501e6cb9237fd7718f9e25
5f208db0be37ce7958c59527
5dc07e2aa60b873d6b0666d1
5f493e73be37ce64d0ae36c7
592486bde410d61fcea3d125
5a5d10b5e4b06ba572cf2497
5fb81985be37ce522e165cdb
5fb81718be37ce522e165cd6
5fb817e8be37ce522e165cd8
5fb818abbe37ce522e165cd9
5fb7f9c2be37ce522e165cc8
5fb81796be37ce522e165cd7
5fb7f8febe37ce522e165cc7
5fb80a6bbe37ce522e165cd0
5fb6d68abe37ce522e165cbf
5fb6d5e4be37ce522e165cbe
5fb7e90fbe37ce522e165cc5
5fb7e52abe37ce522e165cc2
5fb7e7aebe37ce522e165cc4
5fb80e12be37ce522e165cd4
5fb80e70be37ce522e165cd5
5fb7fae8be37ce522e165cca
5f38578fbe37ce5178517ad5
5f441281be37ce5dbe9b7c84
5a5d25b6e4b0db471c2d042c
5332f807e4b03c9a25efd16f
585a9618e4b03e62d1ce0e75
5f513ea1be37ce21f1287c06
5f4cffbba475f1050a66b574
57ebc2f0e4b0ac389136a34c
5f7ba932be37ce2f290fb254
5db9e6551dda2c3e1416aea0
5daf60021dda2c3e1416ae9a
5f493e72be37ce64d0ae36c1
5f493dabbe37ce64d0ae36bb
55a58727e4b0d0a65b3693cd
5fd3ae1fbe37ce0d9386bb55
5332fa75e4b03c9a25efd220
5fb80dd6be37ce522e165cd3
5c49d24df0276e771967371a
5a8c36a1e4b0ccf165fac9e8
5f4a64e7be37ce17d23b317c
57ebc13de4b0ac389136a33e
57d9612be4b0ac389136a2ba
5a8c2f7ce4b0ccf165fac9e3
5f16f536be37ce2b30061e26
5a4d254ce4b0bcb2c74ea780
5fb6d83cbe37ce522e165cc1
5ff74126be37ce1e961f3271
5ff74126be37ce1e961f326f
5ff74126be37ce1e961f3272
5ff744ffbe37ce1e961f3275
5ff74126be37ce1e961f3270

In [4]:
brands[0]

{'_id': {'$oid': '601ac115be37ce2ead437551'},
 'barcode': '511111019862',
 'category': 'Baking',
 'categoryCode': 'BAKING',
 'cpg': {'$id': {'$oid': '601ac114be37ce2ead437550'}, '$ref': 'Cogs'},
 'name': 'test brand @1612366101024',
 'topBrand': False}

In [5]:
if type(brandsdict) == list:
    first_record = brands[0]

In [6]:
#Getting coloumn names

columns_brand = list(brands[0].keys())
print ("\ncolumn names:", columns_brand)

column names: ['_id', 'barcode', 'category', 'categoryCode', 'cpg', 'name', 'topBrand']

In [7]:
columns_brand = [list(brandsdict.keys()) for x in brands[0]][0]

In [8]:
table_name = "brand_data"
sql_string = 'INSERT INTO {} '.format( table_name )
sql_string += "(" + ', '.join(columns_brand) + ")\nVALUES "

In [9]:
brands[0]["cpg"]["$id"]["$oid"]

'601ac114be37ce2ead437550'

### After some exploration, I felt that using just the JSON package, exploding the data stored in multi levels  coloumns was becoming more time taking. Hence I moved to the Pandas package using which I could easily read as well as explode the coloumn data.

In [10]:
import gzip
import shutil
import os
import pandas as pd
from ast import literal_eval
import json
from datetime import datetime
from sqlalchemy import create_engine

pd.set_option('display.max_columns', None)

In [11]:
receipts_data = pd.read_json('receipts.json',lines=True)
brands_data = pd.read_json('brands.json',lines=True)
users_data = pd.read_json('users.json',lines=True)

In [12]:
receipts_data.head()

,_id,bonusPointsEarned,bonusPointsEarnedReason,createDate,dateScanned,finishedDate,modifyDate,pointsAwardedDate,pointsEarned,purchaseDate,purchasedItemCount,rewardsReceiptItemList,rewardsReceiptStatus,totalSpent,userId
0,{'$oid': '5ff1e1eb0a720f0523000575'},500.0,"Receipt number 2 completed, bonus point schedu...",{'$date': 1609687531000},{'$date': 1609687531000},{'$date': 1609687531000},{'$date': 1609687536000},{'$date': 1609687531000},500.0,{'$date': 1609632000000},5.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,26.0,5ff1e1eacfcf6c399c274ae6
1,{'$oid': '5ff1e1bb0a720f052300056b'},150.0,"Receipt number 5 completed, bonus point schedu...",{'$date': 1609687483000},{'$date': 1609687483000},{'$date': 1609687483000},{'$date': 1609687488000},{'$date': 1609687483000},150.0,{'$date': 1609601083000},2.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,11.0,5ff1e194b6a9d73a3a9f1052
2,{'$oid': '5ff1e1f10a720f052300057a'},5.0,All-receipts receipt bonus,{'$date': 1609687537000},{'$date': 1609687537000},NaN,{'$date': 1609687542000},NaN,5.0,{'$date': 1609632000000},1.0,"[{'needsFetchReview': False, 'partnerItemId': ...",REJECTED,10.0,5ff1e1f1cfcf6c399c274b0b
3,{'$oid': '5ff1e1ee0a7214ada100056f'},5.0,All-receipts receipt bonus,{'$date': 1609687534000},{'$date': 1609687534000},{'$date': 1609687534000},{'$date': 1609687539000},{'$date': 1609687534000},5.0,{'$date': 1609632000000},4.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,28.0,5ff1e1eacfcf6c399c274ae6
4,{'$oid': '5ff1e1d20a7214ada1000561'},5.0,All-receipts receipt bonus,{'$date': 1609687506000},{'$date': 1609687506000},{'$date': 1609687511000},{'$date': 1609687511000},{'$date': 1609687506000},5.0,{'$date': 1609601106000},2.0,"[{'barcode': '4011', 'description': 'ITEM NOT ...",FINISHED,1.0,5ff1e194b6a9d73a3a9f1052

In [13]:
brands_data.head()

,_id,barcode,category,categoryCode,cpg,name,topBrand,brandCode
0,{'$oid': '601ac115be37ce2ead437551'},511111019862,Baking,BAKING,"{'$id': {'$oid': '601ac114be37ce2ead437550'}, ...",test brand @1612366101024,0.0,NaN
1,{'$oid': '601c5460be37ce2ead43755f'},511111519928,Beverages,BEVERAGES,"{'$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}, ...",Starbucks,0.0,STARBUCKS
2,{'$oid': '601ac142be37ce2ead43755d'},511111819905,Baking,BAKING,"{'$id': {'$oid': '601ac142be37ce2ead437559'}, ...",test brand @1612366146176,0.0,TEST BRANDCODE @1612366146176
3,{'$oid': '601ac142be37ce2ead43755a'},511111519874,Baking,BAKING,"{'$id': {'$oid': '601ac142be37ce2ead437559'}, ...",test brand @1612366146051,0.0,TEST BRANDCODE @1612366146051
4,{'$oid': '601ac142be37ce2ead43755e'},511111319917,Candy & Sweets,CANDY_AND_SWEETS,"{'$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}, ...",test brand @1612366146827,0.0,TEST BRANDCODE @1612366146827

In [14]:
users_data.head()

,_id,active,createdDate,lastLogin,role,signUpSource,state
0,{'$oid': '5ff1e194b6a9d73a3a9f1052'},True,{'$date': 1609687444800},{'$date': 1609687537858},consumer,Email,WI
1,{'$oid': '5ff1e194b6a9d73a3a9f1052'},True,{'$date': 1609687444800},{'$date': 1609687537858},consumer,Email,WI
2,{'$oid': '5ff1e194b6a9d73a3a9f1052'},True,{'$date': 1609687444800},{'$date': 1609687537858},consumer,Email,WI
3,{'$oid': '5ff1e1eacfcf6c399c274ae6'},True,{'$date': 1609687530554},{'$date': 1609687530597},consumer,Email,WI
4,{'$oid': '5ff1e194b6a9d73a3a9f1052'},True,{'$date': 1609687444800},{'$date': 1609687537858},consumer,Email,WI

An initial problem that I discovered was that brands table had several brands in there, however not all could be mapped  with the brandcode present in the Receipts table. I also found speeling mistakes in few brands leading tto a mismatch, e.g. brands table had "BEN & JERRY'S" while receipts table had "BEN AND JERRYS".

### Exploding the 'rewardsReceiptItemList' coloumn data from receipts_data table as it contains lot of relevant information and also a key value (brandcode) which we can later use to apply joins fron brand_data table

In [15]:
receipts_data = receipts_data.explode('rewardsReceiptItemList')

In [16]:
receipts_data.head()

,_id,bonusPointsEarned,bonusPointsEarnedReason,createDate,dateScanned,finishedDate,modifyDate,pointsAwardedDate,pointsEarned,purchaseDate,purchasedItemCount,rewardsReceiptItemList,rewardsReceiptStatus,totalSpent,userId
0,{'$oid': '5ff1e1eb0a720f0523000575'},500.0,"Receipt number 2 completed, bonus point schedu...",{'$date': 1609687531000},{'$date': 1609687531000},{'$date': 1609687531000},{'$date': 1609687536000},{'$date': 1609687531000},500.0,{'$date': 1609632000000},5.0,"{'barcode': '4011', 'description': 'ITEM NOT F...",FINISHED,26.0,5ff1e1eacfcf6c399c274ae6
1,{'$oid': '5ff1e1bb0a720f052300056b'},150.0,"Receipt number 5 completed, bonus point schedu...",{'$date': 1609687483000},{'$date': 1609687483000},{'$date': 1609687483000},{'$date': 1609687488000},{'$date': 1609687483000},150.0,{'$date': 1609601083000},2.0,"{'barcode': '4011', 'description': 'ITEM NOT F...",FINISHED,11.0,5ff1e194b6a9d73a3a9f1052
1,{'$oid': '5ff1e1bb0a720f052300056b'},150.0,"Receipt number 5 completed, bonus point schedu...",{'$date': 1609687483000},{'$date': 1609687483000},{'$date': 1609687483000},{'$date': 1609687488000},{'$date': 1609687483000},150.0,{'$date': 1609601083000},2.0,"{'barcode': '028400642255', 'description': 'DO...",FINISHED,11.0,5ff1e194b6a9d73a3a9f1052
2,{'$oid': '5ff1e1f10a720f052300057a'},5.0,All-receipts receipt bonus,{'$date': 1609687537000},{'$date': 1609687537000},NaN,{'$date': 1609687542000},NaN,5.0,{'$date': 1609632000000},1.0,"{'needsFetchReview': False, 'partnerItemId': '...",REJECTED,10.0,5ff1e1f1cfcf6c399c274b0b
3,{'$oid': '5ff1e1ee0a7214ada100056f'},5.0,All-receipts receipt bonus,{'$date': 1609687534000},{'$date': 1609687534000},{'$date': 1609687534000},{'$date': 1609687539000},{'$date': 1609687534000},5.0,{'$date': 1609632000000},4.0,"{'barcode': '4011', 'description': 'ITEM NOT F...",FINISHED,28.0,5ff1e1eacfcf6c399c274ae6

In [17]:
receipts_data.reset_index(inplace=True)

In [18]:
receipts_data = receipts_data.fillna({'rewardsReceiptItemList':'{}'})

In [19]:
receipts_data.isna().sum()

index                         0
_id                           0
bonusPointsEarned          1401
bonusPointsEarnedReason    1401
createDate                    0
dateScanned                   0
finishedDate               1411
modifyDate                    0
pointsAwardedDate          1301
pointsEarned               1128
purchaseDate                458
purchasedItemCount          484
rewardsReceiptItemList        0
rewardsReceiptStatus          0
totalSpent                  435
userId                        0
dtype: int64

In [20]:
receipts_data = receipts_data.fillna({'rewardsReceiptItemList':'{}'})

In [21]:
receipts_data['rewardsReceiptItemList'] = receipts_data['rewardsReceiptItemList'].apply(lambda x:str(x))
receipts_data['rewardsReceiptItemList'] = receipts_data['rewardsReceiptItemList'].apply(literal_eval)

In [22]:
receipts_data.rewardsReceiptItemList

0       {'barcode': '4011', 'description': 'ITEM NOT F...
1       {'barcode': '4011', 'description': 'ITEM NOT F...
2       {'barcode': '028400642255', 'description': 'DO...
3       {'needsFetchReview': False, 'partnerItemId': '...
4       {'barcode': '4011', 'description': 'ITEM NOT F...
                              ...
7376                                                   {}
7377                                                   {}
7378    {'barcode': 'B076FJ92M4', 'description': 'muel...
7379    {'barcode': 'B07BRRLSVC', 'description': 'thin...
7380                                                   {}
Name: rewardsReceiptItemList, Length: 7381, dtype: object

In [23]:
type(receipts_data.rewardsReceiptItemList[0])

dict

In [24]:
rewardsReceiptItemList = pd.json_normalize(receipts_data['rewardsReceiptItemList'],errors='ignore',record_prefix='ItemList')\
.add_prefix('ItemList_')

In [25]:
# pd.set_option('display.max_rows', None, 'display.max_columns', None)
rewardsReceiptItemList

,ItemList_barcode,ItemList_description,ItemList_finalPrice,ItemList_itemPrice,ItemList_needsFetchReview,ItemList_partnerItemId,ItemList_preventTargetGapPoints,ItemList_quantityPurchased,ItemList_userFlaggedBarcode,ItemList_userFlaggedNewItem,ItemList_userFlaggedPrice,ItemList_userFlaggedQuantity,ItemList_needsFetchReviewReason,ItemList_pointsNotAwardedReason,ItemList_pointsPayerId,ItemList_rewardsGroup,ItemList_rewardsProductPartnerId,ItemList_userFlaggedDescription,ItemList_originalMetaBriteBarcode,ItemList_originalMetaBriteDescription,ItemList_brandCode,ItemList_competitorRewardsGroup,ItemList_discountedItemPrice,ItemList_originalReceiptItemText,ItemList_itemNumber,ItemList_originalMetaBriteQuantityPurchased,ItemList_pointsEarned,ItemList_targetPrice,ItemList_competitiveProduct,ItemList_originalFinalPrice,ItemList_originalMetaBriteItemPrice,ItemList_deleted,ItemList_priceAfterCoupon,ItemList_metabriteCampaignId
0,4011,ITEM NOT FOUND,26.00,26.00,False,1,True,5.0,4011,True,26.00,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4011,ITEM NOT FOUND,1,1,NaN,1,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,028400642255,DORITOS TORTILLA CHIP SPICY SWEET CHILI REDUCE...,10.00,10.00,True,2,True,1.0,028400642255,True,10.00,1.0,USER_FLAGGED,Action not allowed for user and CPG,5332f5fbe4b03c9a25efd0ba,DORITOS SPICY SWEET CHILI SINGLE SERVE,5332f5fbe4b03c9a25efd0ba,DORITOS TORTILLA CHIP SPICY SWEET CHILI REDUCE...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,False,1,True,NaN,4011,True,26.00,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4011,ITEM NOT FOUND,28.00,28.00,False,1,True,4.0,4011,True,28.00,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7376,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7377,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7378,B076FJ92M4,mueller austria hypergrind precision electric ...,22.97,22.97,NaN,0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.97,mueller austria hypergrind precision electric ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.97,NaN
7379,B07BRRLSVC,thindust summer face mask - sun protection nec...,11.99,11.99,NaN,1,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.99,thindust summer face mask - sun protection nec...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.99,NaN
7380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
receipts_merge = pd.merge(receipts_data, rewardsReceiptItemList, left_index=True, right_index=True, how='outer')

In [27]:
receipts_merge

,index,_id,bonusPointsEarned,bonusPointsEarnedReason,createDate,dateScanned,finishedDate,modifyDate,pointsAwardedDate,pointsEarned,purchaseDate,purchasedItemCount,rewardsReceiptItemList,rewardsReceiptStatus,totalSpent,userId,ItemList_barcode,ItemList_description,ItemList_finalPrice,ItemList_itemPrice,ItemList_needsFetchReview,ItemList_partnerItemId,ItemList_preventTargetGapPoints,ItemList_quantityPurchased,ItemList_userFlaggedBarcode,ItemList_userFlaggedNewItem,ItemList_userFlaggedPrice,ItemList_userFlaggedQuantity,ItemList_needsFetchReviewReason,ItemList_pointsNotAwardedReason,ItemList_pointsPayerId,ItemList_rewardsGroup,ItemList_rewardsProductPartnerId,ItemList_userFlaggedDescription,ItemList_originalMetaBriteBarcode,ItemList_originalMetaBriteDescription,ItemList_brandCode,ItemList_competitorRewardsGroup,ItemList_discountedItemPrice,ItemList_originalReceiptItemText,ItemList_itemNumber,ItemList_originalMetaBriteQuantityPurchased,ItemList_pointsEarned,ItemList_targetPrice,ItemList_competitiveProduct,ItemList_originalFinalPrice,ItemList_originalMetaBriteItemPrice,ItemList_deleted,ItemList_priceAfterCoupon,ItemList_metabriteCampaignId
0,0,{'$oid': '5ff1e1eb0a720f0523000575'},500.0,"Receipt number 2 completed, bonus point schedu...",{'$date': 1609687531000},{'$date': 1609687531000},{'$date': 1609687531000},{'$date': 1609687536000},{'$date': 1609687531000},500.0,{'$date': 1609632000000},5.0,"{'barcode': '4011', 'description': 'ITEM NOT F...",FINISHED,26.00,5ff1e1eacfcf6c399c274ae6,4011,ITEM NOT FOUND,26.00,26.00,False,1,True,5.0,4011,True,26.00,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,{'$oid': '5ff1e1bb0a720f052300056b'},150.0,"Receipt number 5 completed, bonus point schedu...",{'$date': 1609687483000},{'$date': 1609687483000},{'$date': 1609687483000},{'$date': 1609687488000},{'$date': 1609687483000},150.0,{'$date': 1609601083000},2.0,"{'barcode': '4011', 'description': 'ITEM NOT F...",FINISHED,11.00,5ff1e194b6a9d73a3a9f1052,4011,ITEM NOT FOUND,1,1,NaN,1,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,{'$oid': '5ff1e1bb0a720f052300056b'},150.0,"Receipt number 5 completed, bonus point schedu...",{'$date': 1609687483000},{'$date': 1609687483000},{'$date': 1609687483000},{'$date': 1609687488000},{'$date': 1609687483000},150.0,{'$date': 1609601083000},2.0,"{'barcode': '028400642255', 'description': 'DO...",FINISHED,11.00,5ff1e194b6a9d73a3a9f1052,028400642255,DORITOS TORTILLA CHIP SPICY SWEET CHILI REDUCE...,10.00,10.00,True,2,True,1.0,028400642255,True,10.00,1.0,USER_FLAGGED,Action not allowed for user and CPG,5332f5fbe4b03c9a25efd0ba,DORITOS SPICY SWEET CHILI SINGLE SERVE,5332f5fbe4b03c9a25efd0ba,DORITOS TORTILLA CHIP SPICY SWEET CHILI REDUCE...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,{'$oid': '5ff1e1f10a720f052300057a'},5.0,All-receipts receipt bonus,{'$date': 1609687537000},{'$date': 1609687537000},NaN,{'$date': 1609687542000},NaN,5.0,{'$date': 1609632000000},1.0,"{'needsFetchReview': False, 'partnerItemId': '...",REJECTED,10.00,5ff1e1f1cfcf6c399c274b0b,NaN,NaN,NaN,NaN,False,1,True,NaN,4011,True,26.00,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3,{'$oid': '5ff1e1ee0a7214ada100056f'},5.0,All-receipts receipt bonus,{'$date': 1609687534000},{'$date': 1609687534000},{'$date': 1609687534000},{'$date': 1609687539000},{'$date': 1609687534000},5.0,{'$date': 1609632000000},4.0,"{'barcode': '4011', 'description': 'ITEM NOT F...",FINISHED,28.00,5ff1e1eacfcf6c399c274ae6,4011,ITEM NOT FOUND,28.00,28.00,False,1,True,4.0,4011,True,28.00,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7376,1115,{'$oid': '603d0b710a720fde1000042a'},NaN,NaN,{'$date': 1614613361873},{'$date': 1614613361873},NaN,{'$date': 1614613361873},NaN,NaN,NaN,NaN,{},SUBMITTED,NaN,5fc961c3b8cfca11a077dd33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7377,1116,{'$oid': '603cf5290a720fde10000413'},NaN,NaN,{'$date': 1614607657664},{'$date': 1614607657664},NaN,{'$date': 1614607657664},NaN,NaN,NaN,NaN,{},SUBMITTED,NaN,5fc961c3b8cfca11a077dd33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7378,1117,{'$oid': '603ce7100a7217c72c000405'},25.0,COMPLETE_NONPARTNER_RECEIPT,{'$date': 1614604048000},{'$date': 1614604048000},NaN,{'$date': 1614604049000},NaN,25.0,{'$date': 1597622400000},2.0,"{'barcode': 'B076FJ92M4', 'description': 'muel...",REJECTED,34.96,5fc961c3b8cfca11a077dd33,B076FJ92M4,mueller austria hypergrind precision electric ...,22.97,22.97,NaN,0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.97,mueller austria hypergrind precision electric ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.97,NaN
7379,1117,{'$oid': '603ce7100a7217c72c000405'},25.0,COMPLETE_NONPARTNER_RECEIPT,{'$date': 1614604048000},{'$date': 1614604048000},NaN,{'$date': 1614604049000},NaN,25.0,{'$date': 1597622400000},2.0,"{'barcode': 'B07BRRLSVC', 'description': 'thin...",REJECTED,34.96,5fc961c3b8cfca11a077dd33,B07BRRLSVC,thindust summer face mask - sun protection nec...,11.99,11.99,NaN,1,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.99,thindust summer face mask - sun protection nec...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.99,NaN
7380,1118,{'$oid': '603c4fea0a7217c72c000389'},NaN,NaN,{'$date': 1614565354962},{'$date': 1614565354962},NaN,{'$date': 1614565354962},NaN,NaN,NaN,NaN,{},SUBMITTED,NaN,5fc961c3b8cfca11a077dd33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Now we still have coloumns other than the new exploded from rewardsReceiptItemList which are present in the form of dictionery, hence extracting the key values from their to make the dataset uniform

In [28]:
#Before extracting keys, dropping the NA values from date coloumns as those represent incomplete receipts

receipts_merge = receipts_merge.fillna({"finishedDate":"{}"})
receipts_merge = receipts_merge.fillna({"pointsAwardedDate":"{}"})
receipts_merge = receipts_merge.fillna({"purchaseDate":"{}"})

In [31]:
receipts_merge

,index,_id,bonusPointsEarned,bonusPointsEarnedReason,createDate,dateScanned,finishedDate,modifyDate,pointsAwardedDate,pointsEarned,purchaseDate,purchasedItemCount,rewardsReceiptItemList,rewardsReceiptStatus,totalSpent,userId,ItemList_barcode,ItemList_description,ItemList_finalPrice,ItemList_itemPrice,ItemList_needsFetchReview,ItemList_partnerItemId,ItemList_preventTargetGapPoints,ItemList_quantityPurchased,ItemList_userFlaggedBarcode,ItemList_userFlaggedNewItem,ItemList_userFlaggedPrice,ItemList_userFlaggedQuantity,ItemList_needsFetchReviewReason,ItemList_pointsNotAwardedReason,ItemList_pointsPayerId,ItemList_rewardsGroup,ItemList_rewardsProductPartnerId,ItemList_userFlaggedDescription,ItemList_originalMetaBriteBarcode,ItemList_originalMetaBriteDescription,ItemList_brandCode,ItemList_competitorRewardsGroup,ItemList_discountedItemPrice,ItemList_originalReceiptItemText,ItemList_itemNumber,ItemList_originalMetaBriteQuantityPurchased,ItemList_pointsEarned,ItemList_targetPrice,ItemList_competitiveProduct,ItemList_originalFinalPrice,ItemList_originalMetaBriteItemPrice,ItemList_deleted,ItemList_priceAfterCoupon,ItemList_metabriteCampaignId
0,0,{'$oid': '5ff1e1eb0a720f0523000575'},500.0,"Receipt number 2 completed, bonus point schedu...",{'$date': 1609687531000},{'$date': 1609687531000},{'$date': 1609687531000},{'$date': 1609687536000},{'$date': 1609687531000},500.0,{'$date': 1609632000000},5.0,"{'barcode': '4011', 'description': 'ITEM NOT F...",FINISHED,26.00,5ff1e1eacfcf6c399c274ae6,4011,ITEM NOT FOUND,26.00,26.00,False,1,True,5.0,4011,True,26.00,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,{'$oid': '5ff1e1bb0a720f052300056b'},150.0,"Receipt number 5 completed, bonus point schedu...",{'$date': 1609687483000},{'$date': 1609687483000},{'$date': 1609687483000},{'$date': 1609687488000},{'$date': 1609687483000},150.0,{'$date': 1609601083000},2.0,"{'barcode': '4011', 'description': 'ITEM NOT F...",FINISHED,11.00,5ff1e194b6a9d73a3a9f1052,4011,ITEM NOT FOUND,1,1,NaN,1,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,{'$oid': '5ff1e1bb0a720f052300056b'},150.0,"Receipt number 5 completed, bonus point schedu...",{'$date': 1609687483000},{'$date': 1609687483000},{'$date': 1609687483000},{'$date': 1609687488000},{'$date': 1609687483000},150.0,{'$date': 1609601083000},2.0,"{'barcode': '028400642255', 'description': 'DO...",FINISHED,11.00,5ff1e194b6a9d73a3a9f1052,028400642255,DORITOS TORTILLA CHIP SPICY SWEET CHILI REDUCE...,10.00,10.00,True,2,True,1.0,028400642255,True,10.00,1.0,USER_FLAGGED,Action not allowed for user and CPG,5332f5fbe4b03c9a25efd0ba,DORITOS SPICY SWEET CHILI SINGLE SERVE,5332f5fbe4b03c9a25efd0ba,DORITOS TORTILLA CHIP SPICY SWEET CHILI REDUCE...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,{'$oid': '5ff1e1f10a720f052300057a'},5.0,All-receipts receipt bonus,{'$date': 1609687537000},{'$date': 1609687537000},{},{'$date': 1609687542000},{},5.0,{'$date': 1609632000000},1.0,"{'needsFetchReview': False, 'partnerItemId': '...",REJECTED,10.00,5ff1e1f1cfcf6c399c274b0b,NaN,NaN,NaN,NaN,False,1,True,NaN,4011,True,26.00,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3,{'$oid': '5ff1e1ee0a7214ada100056f'},5.0,All-receipts receipt bonus,{'$date': 1609687534000},{'$date': 1609687534000},{'$date': 1609687534000},{'$date': 1609687539000},{'$date': 1609687534000},5.0,{'$date': 1609632000000},4.0,"{'barcode': '4011', 'description': 'ITEM NOT F...",FINISHED,28.00,5ff1e1eacfcf6c399c274ae6,4011,ITEM NOT FOUND,28.00,28.00,False,1,True,4.0,4011,True,28.00,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7376,1115,{'$oid': '603d0b710a720fde1000042a'},NaN,NaN,{'$date': 1614613361873},{'$date': 1614613361873},{},{'$date': 1614613361873},{},NaN,{},NaN,{},SUBMITTED,NaN,5fc961c3b8cfca11a077dd33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7377,1116,{'$oid': '603cf5290a720fde10000413'},NaN,NaN,{'$date': 1614607657664},{'$date': 1614607657664},{},{'$date': 1614607657664},{},NaN,{},NaN,{},SUBMITTED,NaN,5fc961c3b8cfca11a077dd33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7378,1117,{'$oid': '603ce7100a7217c72c000405'},25.0,COMPLETE_NONPARTNER_RECEIPT,{'$date': 1614604048000},{'$date': 1614604048000},{},{'$date': 1614604049000},{},25.0,{'$date': 1597622400000},2.0,"{'barcode': 'B076FJ92M4', 'description': 'muel...",REJECTED,34.96,5fc961c3b8cfca11a077dd33,B076FJ92M4,mueller austria hypergrind precision electric ...,22.97,22.97,NaN,0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.97,mueller austria hypergrind precision electric ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.97,NaN
7379,1117,{'$oid': '603ce7100a7217c72c000405'},25.0,COMPLETE_NONPARTNER_RECEIPT,{'$date': 1614604048000},{'$date': 1614604048000},{},{'$date': 1614604049000},{},25.0,{'$date': 1597622400000},2.0,"{'barcode': 'B07BRRLSVC', 'description': 'thin...",REJECTED,34.96,5fc961c3b8cfca11a077dd33,B07BRRLSVC,thindust summer face mask - sun protection nec...,11.99,11.99,NaN,1,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.99,thindust summer face mask - sun protection nec...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.99,NaN
7380,1118,{'$oid': '603c4fea0a7217c72c000389'},NaN,NaN,{'$date': 1614565354962},{'$date': 1614565354962},{},{'$date': 1614565354962},{},NaN,{},NaN,{},SUBMITTED,NaN,5fc961c3b8cfca11a077dd33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
type(receipts_merge['finishedDate'][3])

str

In [33]:
#Going order wise:

receipts_merge['_id'] = receipts_merge['_id'].apply(lambda x: x['$oid'])

receipts_merge['createDate'] = receipts_merge['createDate'].apply(lambda x: x['$date'])
# receipts_merge['createDate'] = receipts_merge['createDate'].apply(literal_eval)

receipts_merge['dateScanned'] = receipts_merge['dateScanned'].apply(lambda x: x['$date'])
# receipts_merge['dateScanned'] = receipts_merge['dateScanned'].apply(literal_eval)

receipts_merge['finishedDate'] = receipts_merge['finishedDate'].apply(lambda x: 0 if type(x) == str else x['$date'])
# receipts_merge['finishedDate'] = receipts_merge['finishedDate'].apply(literal_eval)

receipts_merge['modifyDate'] = receipts_merge['modifyDate'].apply(lambda x: x['$date'])
# receipts_merge['modifyDate'] = receipts_merge['modifyDate'].apply(literal_eval)

receipts_merge['pointsAwardedDate'] = receipts_merge['pointsAwardedDate'].apply(lambda x: 0 if type(x) == str else x['$date'])
# receipts_merge['pointsAwardedDate'] = receipts_merge['pointsAwardedDate'].apply(literal_eval)

receipts_merge['purchaseDate'] = receipts_merge['purchaseDate'].apply(lambda x: 0 if type(x) == str else x['$date'])
# receipts_merge['purchaseDate'] = receipts_merge['purchaseDate'].apply(literal_eval)

In [34]:
receipts_merge

,index,_id,bonusPointsEarned,bonusPointsEarnedReason,createDate,dateScanned,finishedDate,modifyDate,pointsAwardedDate,pointsEarned,purchaseDate,purchasedItemCount,rewardsReceiptItemList,rewardsReceiptStatus,totalSpent,userId,ItemList_barcode,ItemList_description,ItemList_finalPrice,ItemList_itemPrice,ItemList_needsFetchReview,ItemList_partnerItemId,ItemList_preventTargetGapPoints,ItemList_quantityPurchased,ItemList_userFlaggedBarcode,ItemList_userFlaggedNewItem,ItemList_userFlaggedPrice,ItemList_userFlaggedQuantity,ItemList_needsFetchReviewReason,ItemList_pointsNotAwardedReason,ItemList_pointsPayerId,ItemList_rewardsGroup,ItemList_rewardsProductPartnerId,ItemList_userFlaggedDescription,ItemList_originalMetaBriteBarcode,ItemList_originalMetaBriteDescription,ItemList_brandCode,ItemList_competitorRewardsGroup,ItemList_discountedItemPrice,ItemList_originalReceiptItemText,ItemList_itemNumber,ItemList_originalMetaBriteQuantityPurchased,ItemList_pointsEarned,ItemList_targetPrice,ItemList_competitiveProduct,ItemList_originalFinalPrice,ItemList_originalMetaBriteItemPrice,ItemList_deleted,ItemList_priceAfterCoupon,ItemList_metabriteCampaignId
0,0,5ff1e1eb0a720f0523000575,500.0,"Receipt number 2 completed, bonus point schedu...",1609687531000,1609687531000,1609687531000,1609687536000,1609687531000,500.0,1609632000000,5.0,"{'barcode': '4011', 'description': 'ITEM NOT F...",FINISHED,26.00,5ff1e1eacfcf6c399c274ae6,4011,ITEM NOT FOUND,26.00,26.00,False,1,True,5.0,4011,True,26.00,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,5ff1e1bb0a720f052300056b,150.0,"Receipt number 5 completed, bonus point schedu...",1609687483000,1609687483000,1609687483000,1609687488000,1609687483000,150.0,1609601083000,2.0,"{'barcode': '4011', 'description': 'ITEM NOT F...",FINISHED,11.00,5ff1e194b6a9d73a3a9f1052,4011,ITEM NOT FOUND,1,1,NaN,1,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,5ff1e1bb0a720f052300056b,150.0,"Receipt number 5 completed, bonus point schedu...",1609687483000,1609687483000,1609687483000,1609687488000,1609687483000,150.0,1609601083000,2.0,"{'barcode': '028400642255', 'description': 'DO...",FINISHED,11.00,5ff1e194b6a9d73a3a9f1052,028400642255,DORITOS TORTILLA CHIP SPICY SWEET CHILI REDUCE...,10.00,10.00,True,2,True,1.0,028400642255,True,10.00,1.0,USER_FLAGGED,Action not allowed for user and CPG,5332f5fbe4b03c9a25efd0ba,DORITOS SPICY SWEET CHILI SINGLE SERVE,5332f5fbe4b03c9a25efd0ba,DORITOS TORTILLA CHIP SPICY SWEET CHILI REDUCE...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,5ff1e1f10a720f052300057a,5.0,All-receipts receipt bonus,1609687537000,1609687537000,0,1609687542000,0,5.0,1609632000000,1.0,"{'needsFetchReview': False, 'partnerItemId': '...",REJECTED,10.00,5ff1e1f1cfcf6c399c274b0b,NaN,NaN,NaN,NaN,False,1,True,NaN,4011,True,26.00,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3,5ff1e1ee0a7214ada100056f,5.0,All-receipts receipt bonus,1609687534000,1609687534000,1609687534000,1609687539000,1609687534000,5.0,1609632000000,4.0,"{'barcode': '4011', 'description': 'ITEM NOT F...",FINISHED,28.00,5ff1e1eacfcf6c399c274ae6,4011,ITEM NOT FOUND,28.00,28.00,False,1,True,4.0,4011,True,28.00,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7376,1115,603d0b710a720fde1000042a,NaN,NaN,1614613361873,1614613361873,0,1614613361873,0,NaN,0,NaN,{},SUBMITTED,NaN,5fc961c3b8cfca11a077dd33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7377,1116,603cf5290a720fde10000413,NaN,NaN,1614607657664,1614607657664,0,1614607657664,0,NaN,0,NaN,{},SUBMITTED,NaN,5fc961c3b8cfca11a077dd33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7378,1117,603ce7100a7217c72c000405,25.0,COMPLETE_NONPARTNER_RECEIPT,1614604048000,1614604048000,0,1614604049000,0,25.0,1597622400000,2.0,"{'barcode': 'B076FJ92M4', 'description': 'muel...",REJECTED,34.96,5fc961c3b8cfca11a077dd33,B076FJ92M4,mueller austria hypergrind precision electric ...,22.97,22.97,NaN,0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.97,mueller austria hypergrind precision electric ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.97,NaN
7379,1117,603ce7100a7217c72c000405,25.0,COMPLETE_NONPARTNER_RECEIPT,1614604048000,1614604048000,0,1614604049000,0,25.0,1597622400000,2.0,"{'barcode': 'B07BRRLSVC', 'description': 'thin...",REJECTED,34.96,5fc961c3b8cfca11a077dd33,B07BRRLSVC,thindust summer face mask - sun protection nec...,11.99,11.99,NaN,1,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.99,thindust summer face mask - sun protection nec...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.99,NaN
7380,1118,603c4fea0a7217c72c000389,NaN,NaN,1614565354962,1614565354962,0,1614565354962,0,NaN,0,NaN,{},SUBMITTED,NaN,5fc961c3b8cfca11a077dd33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
type(receipts_merge['createDate'][0])

numpy.int64

In [36]:
import datetime 
receipts_merge['createDate'] = receipts_merge['createDate'].apply(lambda x:datetime.datetime.fromtimestamp(x/1000))
receipts_merge['dateScanned'] = receipts_merge['dateScanned'].apply(lambda x:datetime.datetime.fromtimestamp(x/1000))
receipts_merge['finishedDate'] = receipts_merge['finishedDate'].apply(lambda x:datetime.datetime.fromtimestamp(x/1000))
receipts_merge['modifyDate'] = receipts_merge['modifyDate'].apply(lambda x:datetime.datetime.fromtimestamp(x/1000))
receipts_merge['purchaseDate'] = receipts_merge['purchaseDate'].apply(lambda x:datetime.datetime.fromtimestamp(x/1000))
receipts_merge['pointsAwardedDate'] = receipts_merge['pointsAwardedDate'].apply(lambda x:datetime.datetime.fromtimestamp(x/1000))

In [37]:
receipts_merge

,index,_id,bonusPointsEarned,bonusPointsEarnedReason,createDate,dateScanned,finishedDate,modifyDate,pointsAwardedDate,pointsEarned,purchaseDate,purchasedItemCount,rewardsReceiptItemList,rewardsReceiptStatus,totalSpent,userId,ItemList_barcode,ItemList_description,ItemList_finalPrice,ItemList_itemPrice,ItemList_needsFetchReview,ItemList_partnerItemId,ItemList_preventTargetGapPoints,ItemList_quantityPurchased,ItemList_userFlaggedBarcode,ItemList_userFlaggedNewItem,ItemList_userFlaggedPrice,ItemList_userFlaggedQuantity,ItemList_needsFetchReviewReason,ItemList_pointsNotAwardedReason,ItemList_pointsPayerId,ItemList_rewardsGroup,ItemList_rewardsProductPartnerId,ItemList_userFlaggedDescription,ItemList_originalMetaBriteBarcode,ItemList_originalMetaBriteDescription,ItemList_brandCode,ItemList_competitorRewardsGroup,ItemList_discountedItemPrice,ItemList_originalReceiptItemText,ItemList_itemNumber,ItemList_originalMetaBriteQuantityPurchased,ItemList_pointsEarned,ItemList_targetPrice,ItemList_competitiveProduct,ItemList_originalFinalPrice,ItemList_originalMetaBriteItemPrice,ItemList_deleted,ItemList_priceAfterCoupon,ItemList_metabriteCampaignId
0,0,5ff1e1eb0a720f0523000575,500.0,"Receipt number 2 completed, bonus point schedu...",2021-01-03 10:25:31.000,2021-01-03 10:25:31.000,2021-01-03 10:25:31,2021-01-03 10:25:36.000,2021-01-03 10:25:31,500.0,2021-01-02 19:00:00,5.0,"{'barcode': '4011', 'description': 'ITEM NOT F...",FINISHED,26.00,5ff1e1eacfcf6c399c274ae6,4011,ITEM NOT FOUND,26.00,26.00,False,1,True,5.0,4011,True,26.00,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,5ff1e1bb0a720f052300056b,150.0,"Receipt number 5 completed, bonus point schedu...",2021-01-03 10:24:43.000,2021-01-03 10:24:43.000,2021-01-03 10:24:43,2021-01-03 10:24:48.000,2021-01-03 10:24:43,150.0,2021-01-02 10:24:43,2.0,"{'barcode': '4011', 'description': 'ITEM NOT F...",FINISHED,11.00,5ff1e194b6a9d73a3a9f1052,4011,ITEM NOT FOUND,1,1,NaN,1,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,5ff1e1bb0a720f052300056b,150.0,"Receipt number 5 completed, bonus point schedu...",2021-01-03 10:24:43.000,2021-01-03 10:24:43.000,2021-01-03 10:24:43,2021-01-03 10:24:48.000,2021-01-03 10:24:43,150.0,2021-01-02 10:24:43,2.0,"{'barcode': '028400642255', 'description': 'DO...",FINISHED,11.00,5ff1e194b6a9d73a3a9f1052,028400642255,DORITOS TORTILLA CHIP SPICY SWEET CHILI REDUCE...,10.00,10.00,True,2,True,1.0,028400642255,True,10.00,1.0,USER_FLAGGED,Action not allowed for user and CPG,5332f5fbe4b03c9a25efd0ba,DORITOS SPICY SWEET CHILI SINGLE SERVE,5332f5fbe4b03c9a25efd0ba,DORITOS TORTILLA CHIP SPICY SWEET CHILI REDUCE...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,5ff1e1f10a720f052300057a,5.0,All-receipts receipt bonus,2021-01-03 10:25:37.000,2021-01-03 10:25:37.000,1969-12-31 19:00:00,2021-01-03 10:25:42.000,1969-12-31 19:00:00,5.0,2021-01-02 19:00:00,1.0,"{'needsFetchReview': False, 'partnerItemId': '...",REJECTED,10.00,5ff1e1f1cfcf6c399c274b0b,NaN,NaN,NaN,NaN,False,1,True,NaN,4011,True,26.00,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3,5ff1e1ee0a7214ada100056f,5.0,All-receipts receipt bonus,2021-01-03 10:25:34.000,2021-01-03 10:25:34.000,2021-01-03 10:25:34,2021-01-03 10:25:39.000,2021-01-03 10:25:34,5.0,2021-01-02 19:00:00,4.0,"{'barcode': '4011', 'description': 'ITEM NOT F...",FINISHED,28.00,5ff1e1eacfcf6c399c274ae6,4011,ITEM NOT FOUND,28.00,28.00,False,1,True,4.0,4011,True,28.00,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7376,1115,603d0b710a720fde1000042a,NaN,NaN,2021-03-01 10:42:41.873,2021-03-01 10:42:41.873,1969-12-31 19:00:00,2021-03-01 10:42:41.873,1969-12-31 19:00:00,NaN,1969-12-31 19:00:00,NaN,{},SUBMITTED,NaN,5fc961c3b8cfca11a077dd33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7377,1116,603cf5290a720fde10000413,NaN,NaN,2021-03-01 09:07:37.664,2021-03-01 09:07:37.664,1969-12-31 19:00:00,2021-03-01 09:07:37.664,1969-12-31 19:00:00,NaN,1969-12-31 19:00:00,NaN,{},SUBMITTED,NaN,5fc961c3b8cfca11a077dd33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7378,1117,603ce7100a7217c72c000405,25.0,COMPLETE_NONPARTNER_RECEIPT,2021-03-01 08:07:28.000,2021-03-01 08:07:28.000,1969-12-31 19:00:00,2021-03-01 08:07:29.000,1969-12-31 19:00:00,25.0,2020-08-16 20:00:00,2.0,"{'barcode': 'B076FJ92M4', 'description': 'muel...",REJECTED,34.96,5fc961c3b8cfca11a077dd33,B076FJ92M4,mueller austria hypergrind precision electric ...,22.97,22.97,NaN,0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.97,mueller austria hypergrind precision electric ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22.97,NaN
7379,1117,603ce7100a7217c72c000405,25.0,COMPLETE_NONPARTNER_RECEIPT,2021-03-01 08:07:28.000,2021-03-01 08:07:28.000,1969-12-31 19:00:00,2021-03-01 08:07:29.000,1969-12-31 19:00:00,25.0,2020-08-16 20:00:00,2.0,"{'barcode': 'B07BRRLSVC', 'description': 'thin...",REJECTED,34.96,5fc961c3b8cfca11a077dd33,B07BRRLSVC,thindust summer face mask - sun protection nec...,11.99,11.99,NaN,1,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.99,thindust summer face mask - sun protection nec...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.99,NaN
7380,1118,603c4fea0a7217c72c000389,NaN,NaN,2021-02-28 21:22:34.962,2021-02-28 21:22:34.962,1969-12-31 19:00:00,2021-02-28 21:22:34.962,1969-12-31 19:00:00,NaN,1969-12-31 19:00:00,NaN,{},SUBMITTED,NaN,5fc961c3b8cfca11a077dd33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
#Dropping the dict field rewardsReceiptItemList which is present now in the exploded format

receipts_merge = receipts_merge.drop(columns= 'rewardsReceiptItemList')

In [39]:
#Converting coloumn names to lowercase

receipts_merge.columns = receipts_merge.columns.str.lower()

Repeating the process for brands table

In [40]:
brands_data.head()

,_id,barcode,category,categoryCode,cpg,name,topBrand,brandCode
0,{'$oid': '601ac115be37ce2ead437551'},511111019862,Baking,BAKING,"{'$id': {'$oid': '601ac114be37ce2ead437550'}, ...",test brand @1612366101024,0.0,NaN
1,{'$oid': '601c5460be37ce2ead43755f'},511111519928,Beverages,BEVERAGES,"{'$id': {'$oid': '5332f5fbe4b03c9a25efd0ba'}, ...",Starbucks,0.0,STARBUCKS
2,{'$oid': '601ac142be37ce2ead43755d'},511111819905,Baking,BAKING,"{'$id': {'$oid': '601ac142be37ce2ead437559'}, ...",test brand @1612366146176,0.0,TEST BRANDCODE @1612366146176
3,{'$oid': '601ac142be37ce2ead43755a'},511111519874,Baking,BAKING,"{'$id': {'$oid': '601ac142be37ce2ead437559'}, ...",test brand @1612366146051,0.0,TEST BRANDCODE @1612366146051
4,{'$oid': '601ac142be37ce2ead43755e'},511111319917,Candy & Sweets,CANDY_AND_SWEETS,"{'$id': {'$oid': '5332fa12e4b03c9a25efd1e7'}, ...",test brand @1612366146827,0.0,TEST BRANDCODE @1612366146827

Exploding was'nt required in cpg as it is not a list of dictionaries, hence extracting just the oid and reference key values

In [42]:
cpg = pd.json_normalize(brands_data['cpg'],errors='ignore',record_prefix='cpg')\
.add_prefix('cpg_')

In [43]:
_id = pd.json_normalize(brands_data['_id'],errors='ignore',record_prefix='_id')\
.add_prefix('_id')

In [44]:
cpg

     cpg_$ref              cpg_$id.$oid
0        Cogs  601ac114be37ce2ead437550
1        Cogs  5332f5fbe4b03c9a25efd0ba
2        Cogs  601ac142be37ce2ead437559
3        Cogs  601ac142be37ce2ead437559
4        Cogs  5332fa12e4b03c9a25efd1e7
...       ...                       ...
1162     Cogs  5f77274dbe37ce6b592e90bf
1163     Cogs  53e10d6368abd3c7065097cc
1164     Cogs  5332fa12e4b03c9a25efd1e7
1165     Cogs  5332f5f6e4b03c9a25efd0b4
1166     Cogs  6026d757be37ce6369301467

[1167 rows x 2 columns]

In [45]:
brands_merge_t = pd.merge(brands_data, cpg, left_index=True, right_index=True, how='outer')

In [46]:
brands_merge = pd.merge(brands_merge_t, _id, left_index=True, right_index=True, how='outer')

In [47]:
brands_merge = brands_merge.drop(columns=['_id','cpg'])

In [48]:
brands_merge.columns = brands_merge.columns.str.lower()

In [72]:
brands_merge

,barcode,category,categorycode,name,topbrand,brandcode,cpg_$ref,cpg_$id.$oid,_id$oid
0,511111019862,Baking,BAKING,test brand @1612366101024,0.0,NaN,Cogs,601ac114be37ce2ead437550,601ac115be37ce2ead437551
1,511111519928,Beverages,BEVERAGES,Starbucks,0.0,STARBUCKS,Cogs,5332f5fbe4b03c9a25efd0ba,601c5460be37ce2ead43755f
2,511111819905,Baking,BAKING,test brand @1612366146176,0.0,TEST BRANDCODE @1612366146176,Cogs,601ac142be37ce2ead437559,601ac142be37ce2ead43755d
3,511111519874,Baking,BAKING,test brand @1612366146051,0.0,TEST BRANDCODE @1612366146051,Cogs,601ac142be37ce2ead437559,601ac142be37ce2ead43755a
4,511111319917,Candy & Sweets,CANDY_AND_SWEETS,test brand @1612366146827,0.0,TEST BRANDCODE @1612366146827,Cogs,5332fa12e4b03c9a25efd1e7,601ac142be37ce2ead43755e
...,...,...,...,...,...,...,...,...,...
1162,511111116752,Baking,BAKING,test brand @1601644365844,NaN,NaN,Cogs,5f77274dbe37ce6b592e90bf,5f77274dbe37ce6b592e90c0
1163,511111706328,Breakfast & Cereal,NaN,Dippin Dots® Cereal,NaN,DIPPIN DOTS CEREAL,Cogs,53e10d6368abd3c7065097cc,5dc1fca91dda2c0ad7da64ae
1164,511111416173,Candy & Sweets,CANDY_AND_SWEETS,test brand @1598639215217,NaN,TEST BRANDCODE @1598639215217,Cogs,5332fa12e4b03c9a25efd1e7,5f494c6e04db711dd8fe87e7
1165,511111400608,Grocery,NaN,LIPTON TEA Leaves,0.0,LIPTON TEA Leaves,Cogs,5332f5f6e4b03c9a25efd0b4,5a021611e4b00efe02b02a57
1166,511111019930,Baking,BAKING,test brand @1613158231643,0.0,TEST BRANDCODE @1613158231644,Cogs,6026d757be37ce6369301467,6026d757be37ce6369301468

No exploding is required in users table, however we will have to extract the key values from the dictionery fields and convert it to string for further processing

In [49]:
users_data.isna().sum()

_id              0
active           0
createdDate      0
lastLogin       62
role             0
signUpSource    48
state           56
dtype: int64

In [50]:
#Dropping NA values

users_data = users_data.dropna(subset=['lastLogin'])

In [51]:
users_data['_id'] = users_data['_id'].apply(lambda x: x['$oid'])

In [52]:
users_data['createdDate'] = users_data['createdDate'].apply(lambda x: x['$date'])

In [53]:
users_data['lastLogin'] = users_data['lastLogin'].apply(lambda x: x['$date'])

In [54]:
users_data.columns = users_data.columns.str.lower()

In [69]:
users_data['createddate'] = users_data['createddate'].apply(lambda x:datetime.datetime.fromtimestamp(x/1000))
users_data['lastlogin'] = users_data['lastlogin'].apply(lambda x:datetime.datetime.fromtimestamp(x/1000))

In [70]:
users_data

,_id,active,createddate,lastlogin,role,signupsource,state
0,5ff1e194b6a9d73a3a9f1052,True,2021-01-03 10:24:04.800,2021-01-03 10:25:37.858,consumer,Email,WI
1,5ff1e194b6a9d73a3a9f1052,True,2021-01-03 10:24:04.800,2021-01-03 10:25:37.858,consumer,Email,WI
2,5ff1e194b6a9d73a3a9f1052,True,2021-01-03 10:24:04.800,2021-01-03 10:25:37.858,consumer,Email,WI
3,5ff1e1eacfcf6c399c274ae6,True,2021-01-03 10:25:30.554,2021-01-03 10:25:30.597,consumer,Email,WI
4,5ff1e194b6a9d73a3a9f1052,True,2021-01-03 10:24:04.800,2021-01-03 10:25:37.858,consumer,Email,WI
...,...,...,...,...,...,...,...
490,54943462e4b07e684157a532,True,2014-12-19 09:21:22.381,2021-03-05 11:52:23.204,fetch-staff,NaN,NaN
491,54943462e4b07e684157a532,True,2014-12-19 09:21:22.381,2021-03-05 11:52:23.204,fetch-staff,NaN,NaN
492,54943462e4b07e684157a532,True,2014-12-19 09:21:22.381,2021-03-05 11:52:23.204,fetch-staff,NaN,NaN
493,54943462e4b07e684157a532,True,2014-12-19 09:21:22.381,2021-03-05 11:52:23.204,fetch-staff,NaN,NaN
494,54943462e4b07e684157a532,True,2014-12-19 09:21:22.381,2021-03-05 11:52:23.204,fetch-staff,NaN,NaN

In [55]:
#Exctracting coloumn names of new tables

columns_receipts = print(receipts_merge.columns)

Index(['index', '_id', 'bonuspointsearned', 'bonuspointsearnedreason',
       'createdate', 'datescanned', 'finisheddate', 'modifydate',
       'pointsawardeddate', 'pointsearned', 'purchasedate',
       'purchaseditemcount', 'rewardsreceiptstatus', 'totalspent', 'userid',
       'itemlist_barcode', 'itemlist_description', 'itemlist_finalprice',
       'itemlist_itemprice', 'itemlist_needsfetchreview',
       'itemlist_partneritemid', 'itemlist_preventtargetgappoints',
       'itemlist_quantitypurchased', 'itemlist_userflaggedbarcode',
       'itemlist_userflaggednewitem', 'itemlist_userflaggedprice',
       'itemlist_userflaggedquantity', 'itemlist_needsfetchreviewreason',
       'itemlist_pointsnotawardedreason', 'itemlist_pointspayerid',
       'itemlist_rewardsgroup', 'itemlist_rewardsproductpartnerid',
       'itemlist_userflaggeddescription', 'itemlist_originalmetabritebarcode',
       'itemlist_originalmetabritedescription', 'itemlist_brandcode',
       'itemlist_competitorrewardsgroup', 'itemlist_discounteditemprice',
       'itemlist_originalreceiptitemtext', 'itemlist_itemnumber',
       'itemlist_originalmetabritequantitypurchased', 'itemlist_pointsearned',
       'itemlist_targetprice', 'itemlist_competitiveproduct',
       'itemlist_originalfinalprice', 'itemlist_originalmetabriteitemprice',
       'itemlist_deleted', 'itemlist_priceaftercoupon',
       'itemlist_metabritecampaignid'],
      dtype='object')

In [56]:
receipts_merge.dtypes

index                                                   int64
_id                                                    object
bonuspointsearned                                     float64
bonuspointsearnedreason                                object
createdate                                     datetime64[ns]
datescanned                                    datetime64[ns]
finisheddate                                   datetime64[ns]
modifydate                                     datetime64[ns]
pointsawardeddate                              datetime64[ns]
pointsearned                                          float64
purchasedate                                   datetime64[ns]
purchaseditemcount                                    float64
rewardsreceiptstatus                                   object
totalspent                                            float64
userid                                                 object
itemlist_barcode                                       object
itemlist_description                                   object
itemlist_finalprice                                    object
itemlist_itemprice                                     object
itemlist_needsfetchreview                              object
itemlist_partneritemid                                 object
itemlist_preventtargetgappoints                        object
itemlist_quantitypurchased                            float64
itemlist_userflaggedbarcode                            object
itemlist_userflaggednewitem                            object
itemlist_userflaggedprice                              object
itemlist_userflaggedquantity                          float64
itemlist_needsfetchreviewreason                        object
itemlist_pointsnotawardedreason                        object
itemlist_pointspayerid                                 object
itemlist_rewardsgroup                                  object
itemlist_rewardsproductpartnerid                       object
itemlist_userflaggeddescription                        object
itemlist_originalmetabritebarcode                      object
itemlist_originalmetabritedescription                  object
itemlist_brandcode                                     object
itemlist_competitorrewardsgroup                        object
itemlist_discounteditemprice                           object
itemlist_originalreceiptitemtext                       object
itemlist_itemnumber                                    object
itemlist_originalmetabritequantitypurchased           float64
itemlist_pointsearned                                  object
itemlist_targetprice                                   object
itemlist_competitiveproduct                            object
itemlist_originalfinalprice                            object
itemlist_originalmetabriteitemprice                    object
itemlist_deleted                                       object
itemlist_priceaftercoupon                              object
itemlist_metabritecampaignid                           object
dtype: object

In [57]:
brands_merge.dtypes

barcode           int64
category         object
categorycode     object
name             object
topbrand        float64
brandcode        object
cpg_$ref         object
cpg_$id.$oid     object
_id$oid          object
dtype: object

In [58]:
users_data.dtypes

_id             object
active            bool
createddate      int64
lastlogin        int64
role            object
signupsource    object
state           object
dtype: object

In [59]:
#Connecting to db and creating tables

import time
import pandas as pd
from sqlalchemy import create_engine
import psycopg2

In [60]:
engine = create_engine('postgresql://postgres:password@localhost:5432/fetch_rewards')
receipts_merge.to_sql('receipts', engine)

In [61]:
engine = create_engine('postgresql://postgres:password@localhost:5432/fetch_rewards')
brands_merge.to_sql('brands', engine)

In [71]:
engine = create_engine('postgresql://postgres:password@localhost:5432/fetch_rewards')
users_data.to_sql('users', engine)

## Second: Write a query that directly answers a predetermined question from a business stakeholder

Functioning Queries are submitted in the sql file (queries.sql)

## Third: Evaluate Data Quality Issues in the Data Provided

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

In [75]:
brands_cat = pd.value_counts(brands_merge.category)
brands_cat = pd.DataFrame(brands_cat)

brands_cat.columns =['Category_Count']
brands_cat

                             Category_Count
Baking                                  369
Beer Wine Spirits                        90
Snacks                                   75
Candy & Sweets                           71
Beverages                                63
Health & Wellness                        44
Magazines                                44
Breakfast & Cereal                       40
Grocery                                  39
Dairy                                    33
Condiments & Sauces                      27
Frozen                                   24
Personal Care                            20
Baby                                     18
Canned Goods & Soups                     12
Beauty                                    9
Beauty & Personal Care                    6
Cleaning & Home Improvement               6
Deli                                      6
Household                                 5
Dairy & Refrigerated                      5
Bread & Bakery                            5
Outdoor                                   1

In [78]:
receipts_merge.isna().sum()

index                                             0
_id                                               0
bonuspointsearned                              1401
bonuspointsearnedreason                        1401
createdate                                        0
datescanned                                       0
finisheddate                                      0
modifydate                                        0
pointsawardeddate                                 0
pointsearned                                   1128
purchasedate                                      0
purchaseditemcount                              484
rewardsreceiptstatus                              0
totalspent                                      435
userid                                            0
itemlist_barcode                               4291
itemlist_description                            821
itemlist_finalprice                             614
itemlist_itemprice                              614
itemlist_needsfetchreview                      6568
itemlist_partneritemid                          440
itemlist_preventtargetgappoints                7023
itemlist_quantitypurchased                      614
itemlist_userflaggedbarcode                    7044
itemlist_userflaggednewitem                    7058
itemlist_userflaggedprice                      7082
itemlist_userflaggedquantity                   7082
itemlist_needsfetchreviewreason                7162
itemlist_pointsnotawardedreason                7041
itemlist_pointspayerid                         6114
itemlist_rewardsgroup                          5650
itemlist_rewardsproductpartnerid               5112
itemlist_userflaggeddescription                7176
itemlist_originalmetabritebarcode              7310
itemlist_originalmetabritedescription          7371
itemlist_brandcode                             4781
itemlist_competitorrewardsgroup                7106
itemlist_discounteditemprice                   1612
itemlist_originalreceiptitemtext               1621
itemlist_itemnumber                            7228
itemlist_originalmetabritequantitypurchased    7366
itemlist_pointsearned                          6454
itemlist_targetprice                           7003
itemlist_competitiveproduct                    6736
itemlist_originalfinalprice                    7372
itemlist_originalmetabriteitemprice            7372
itemlist_deleted                               7372
itemlist_priceaftercoupon                      6425
itemlist_metabritecampaignid                   6518
dtype: int64

## Fourth: Communicate with Stakeholders

Construct an email or slack message that is understandable to a product or business leader who isn’t familiar with your day to day work. This part of the exercise should show off how you communicate and reason about data with others. Commit your answers to the git repository along with the rest of your exercise.

What questions do you have about the data?
How did you discover the data quality issues?
What do you need to know to resolve the data quality issues?
What other information would you need to help you optimize the data assets you're trying to create?
What performance and scaling concerns do you anticipate in production and how do you plan to address them?

EMAIL:
    
Dear Team,
    
Hope you are doing well!
    
I performed analytics on fetch_rewards data where I used the given json files (users, brands and receipts).
While cleaning the data using python I relaised the coloumns need to be further exploded as it contained more 
information. After cleaning, I pushed the data to postgres sql database. Some of the insights generated are 
below:
    
1. The first thing I noticed was that not all the Brandcodes in the receipts table matched with those present 
in the brands table. A potential reason for that could be that Fetch Rewards had no partnership with them
    
2. The datasets had a lot of missing values and hence instead of just dropping the entire rows, I decided to 
fill them with NULL values
    
3. Primary key of any dataset wasn't provided upfront. It would have be easier to build relationships between 
the 3 tables in case the keys were provided.
    
4. The multilayering of data in single coloumn, like 'rewardsReceiptItemList' coloumn in receipts table took 
good amount of effort as well as time before I could explode all the data from it.
    
Lastly, I had a few concerns and questions about the discrepancies and duplications present in the data which I would like to discuss over a call. Request you to kindly suggest a suitable time to discuss the same.
    
Thanks & Regrads,                             
Devanshoo Jain